### PR TITLE
Note that integration tests need no-env-filter

### PR DESCRIPTION
**Pull request by sourcefrog**
Follows on from #6

### CODE REVIEW

**Comment by dbrgn** [comment]
Good point, thanks!

Could you move down the new paragraph below the next one? I think it would fit better that way.

**Comment by sourcefrog** [comment]
Done, thanks.

**Comment by sourcefrog** [comment]
p.s. I think it would be nice to somehow make the default for integration tests be that it sees trace from the crate under test but not others. It seems like it should be possible, but perhaps it's complicated.

**Comment by dbrgn** [comment]
> p.s. I think it would be nice to somehow make the default for integration tests be that it sees trace from the crate under test but not others. It seems like it should be possible, but perhaps it's complicated.

If you have an idea, let me know 🙂

**Pull request merged**
