### PR TITLE
Add a log count function

### PR DESCRIPTION
**Pull request by joshuef**
Hey @dbrgn !

I've used the main crate ina  couple of repos, so first thanks for that!

I'm not sure if this would be wanted? But I hope so, as it's useful to us ot ensure certain events are happening the correct number of times. (msgs received eg).

Let me know if you want any changes or more tests eg, and I'll get on it asap.

Cheers!

### CODE REVIEW

**Review by threema-danilo — CHANGES_REQUESTED** [review]
If you rebase against the main branch, the build should work.

However, I'm still not sure whether the whole approach with "line contains this log" is good. With the current approach, a log with the contents `DontCountMe` would be included in the count for `CountMe` as well...

The approach works for "ensure that this snippet was logged somewhere", but once you want to know more detailed information (like "how many times was this logged"), it will start to break down in corner cases.

Maybe you have another idea how the assertions could work? Maybe a function like this could be provided?

```rust
fn logs_assert<F>(f: F) -> Result<(), String> where F: Fn(&[&str]) { ... }
```

With this, the user can pass a closure to `assert_logs` which gets access to the slice of logs. It can then do any assertions it wants. If the assertion fails, it would return `Err(String)`. Counting occurrences of log lines would be possible this way.

**Comment by joshuef** [comment]
>Maybe a function like this could be provided?

Hmm, interesting. Aye, I'll have a poke at your suggestion + general feedback the coming week. 🙇

**Comment by joshuef** [comment]
Okay, so as per the suggestion, I've updated the PR with a more general `logs_run` function, which can take a function and will just pass it the logs so we can do what we want with it.

Also rebased on master and addressed the other comments (as made sense w/ the changes).

Seems to work well enough, and is definitely more flexible. It's not taking a closure though as the compiler was giving me grief about that... It may be possible to get it going, but I'm not sure how myself. Any tips there or other suggestions welcome!

**Comment by threema-danilo** [comment]
> It's not taking a closure though as the compiler was giving me grief about that... It may be possible to get it going, but I'm not sure how myself.

It was easier to do this myself than to explain it, so I pushed a commit to your branch. What do you think about that approach, @joshuef?

The `logs_assert` function is different than `logs_contain` because the latter returns a boolean (which you need to include in an assertion of your own) while the former panics directly if the passed in function returns an error. However, with the function naming, I think that's the best and most ergonomic approach.

**Comment by dbrgn** [comment]
I added some docs, this should be good to merge now. Thanks @joshuef for getting this started!

**Pull request merged**
